/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AviatorProgress } from "./AviatorProgress";
import { AviatorProgressCountArgs } from "./AviatorProgressCountArgs";
import { AviatorProgressFindManyArgs } from "./AviatorProgressFindManyArgs";
import { AviatorProgressFindUniqueArgs } from "./AviatorProgressFindUniqueArgs";
import { DeleteAviatorProgressArgs } from "./DeleteAviatorProgressArgs";
import { AviatorProgressService } from "../aviatorProgress.service";
@graphql.Resolver(() => AviatorProgress)
export class AviatorProgressResolverBase {
  constructor(protected readonly service: AviatorProgressService) {}

  async _aviatorProgressesMeta(
    @graphql.Args() args: AviatorProgressCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AviatorProgress])
  async aviatorProgresses(
    @graphql.Args() args: AviatorProgressFindManyArgs
  ): Promise<AviatorProgress[]> {
    return this.service.aviatorProgresses(args);
  }

  @graphql.Query(() => AviatorProgress, { nullable: true })
  async aviatorProgress(
    @graphql.Args() args: AviatorProgressFindUniqueArgs
  ): Promise<AviatorProgress | null> {
    const result = await this.service.aviatorProgress(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AviatorProgress)
  async deleteAviatorProgress(
    @graphql.Args() args: DeleteAviatorProgressArgs
  ): Promise<AviatorProgress | null> {
    try {
      return await this.service.deleteAviatorProgress(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
