/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  AviatorProgress as PrismaAviatorProgress,
} from "@prisma/client";

export class AviatorProgressServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AviatorProgressCountArgs, "select">
  ): Promise<number> {
    return this.prisma.aviatorProgress.count(args);
  }

  async aviatorProgresses<T extends Prisma.AviatorProgressFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AviatorProgressFindManyArgs>
  ): Promise<PrismaAviatorProgress[]> {
    return this.prisma.aviatorProgress.findMany<Prisma.AviatorProgressFindManyArgs>(
      args
    );
  }
  async aviatorProgress<T extends Prisma.AviatorProgressFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AviatorProgressFindUniqueArgs>
  ): Promise<PrismaAviatorProgress | null> {
    return this.prisma.aviatorProgress.findUnique(args);
  }
  async createAviatorProgress<T extends Prisma.AviatorProgressCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AviatorProgressCreateArgs>
  ): Promise<PrismaAviatorProgress> {
    return this.prisma.aviatorProgress.create<T>(args);
  }
  async updateAviatorProgress<T extends Prisma.AviatorProgressUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AviatorProgressUpdateArgs>
  ): Promise<PrismaAviatorProgress> {
    return this.prisma.aviatorProgress.update<T>(args);
  }
  async deleteAviatorProgress<T extends Prisma.AviatorProgressDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AviatorProgressDeleteArgs>
  ): Promise<PrismaAviatorProgress> {
    return this.prisma.aviatorProgress.delete(args);
  }
}
